########################### Navigation Bar ########################### > start
# 注意事项：建议规范全站路径 URL 最后带一个 "/" 例如 "about/"

# site-related configuration
# 站点相关配置
site:
  favicon: /favicon.ico
  logo: /assets/logo.png
  display_title: false #显示站点名称，true 为显示，false 为不显示

# main menu navigation
menu:
  Home: /
  List:
    Item1: /
    Item2: /
  Link: /
  About: /about/

# mobile menu navigation, Do not have a submenu
mobile_menu:
  Link: /
  Docs: /
  About: /about/
  Contact: /

# mobile menu scroll, If not enabled, please set enable to false
mobile_menu_scroll:
  enable: true
  before: /assets/menu_scroll_before.webp
  after: /assets/menu_scroll_after.webp

# Navigation bar right-side button
nav_button:
  enable: true #导航栏右侧按钮总开关，设置 false 为不显示，以下所有按钮开启了也不会显示
  container:
    enable: true #在导航栏显示内容按钮，设置 false 为不显示
    title: Try for free
    url: /

########################### Navigation Bar ########################### > end


########################### imagesloaded ########################### > start
# TODO：后续学习 JS 后，来运用它，注意：这代码应该改写出 cdn 和内部两块
imagesloaded:
  enable: false
  js:
    src: https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/5.0.0/imagesloaded.pkgd.min.js
    integrity: sha512-kfs3Dt9u9YcOiIt4rNcPUzdyNNO9sVGQPiZsub7ywg6lRW5KuK1m145ImrFHe3LMWXHndoKo2YRXWy8rnOcSKg==
########################### imagesloaded ########################### > end


########################### Slide ########################### > start
# 启用后，本地的 slide js 和 css 将会在 cdn 加载出错时调用，请确保 slide 里的 js 和 css 有设置
swiper_cdnjs:
  enable: true
  js:
    src: https://cdnjs.cloudflare.com/ajax/libs/Swiper/10.2.0/swiper-bundle.min.js
    integrity: sha512-QwpsxtdZRih55GaU/Ce2Baqoy2tEv9GltjAG8yuTy2k9lHqK7VHHp3wWWe+yITYKZlsT3AaCj49ZxMYPp46iJQ==
  css:
    href: https://cdnjs.cloudflare.com/ajax/libs/Swiper/10.2.0/swiper-bundle.min.css
    integrity: sha512-s6khMl5GDS1HbQ5/SwL1wzMayPwHXPjKoBN5kHUTDqKEPkkGyEZWKyH2lQ3YO2q3dxueG3rE0NHjRawMHd2b6g==

slide:
  enable: true
  js: /js/swiper-bundle.min.js # 当 swiper_cdnjs 开启时，只有出错时才会加载本地 swiper js
  css: /css/swiper-bundle.min.css # 当 swiper_cdnjs 开启时，只有出错时才会加载本地 swiper css
  wrapper:
    # TODO: 后续有时间实现 introduce
    # 第一组
    # 图片的 url 为普通的 jpg png gif 等图片格式，url 此值不能为空。avif 和 webp 请专门设置
    - desktop_img: # 建议图片大小是 1080P，2K，4K 等以便在 PC 电脑上显示
        avif_url: /assets/slide/1.avif
        webp_url: /assets/slide/1.webp
        url: /assets/slide/1.jpg
      tablet_img: # 建议图片大小是 768x1024，1024x1336，1536x2048，2048x2732 等平板设备的分辨率
        avif_url: /assets/slide/tablet-1.avif
        webp_url: /assets/slide/tablet-1.webp
        url: /assets/slide/tablet-1.jpg
      mobile_img: # 建议图片大小是 750x1334，780x1387，1125x2436，1242x2208 等移动设备的分辨率
        avif_url: /assets/slide/mobile-1.avif
        webp_url: /assets/slide/mobile-1.webp
        url: /assets/slide/mobile-1.jpg
      introduce:
        position: center
        title: Getting
        subtitle: Wit once bought is worth twice taught
        white_title: false
        button_title: Read more
        button_url: /
    # 第二组
    # 图片的 url 为普通的 jpg png gif 等图片格式，url 此值不能为空。avif 和 webp 请专门设置
    - desktop_img: # 建议图片大小是 1080P，2K，4K 等以便在 PC 电脑上显示
        avif_url: /assets/slide/2.avif
        webp_url: /assets/slide/2.webp
        url: /assets/slide/2.jpg
      tablet_img: # 建议图片大小是 768x1024，1024x1336，1536x2048，2048x2732 等平板设备的分辨率
        avif_url: /assets/slide/tablet-2.avif
        webp_url: /assets/slide/tablet-2.webp
        url: /assets/slide/tablet-2.jpg
      mobile_img: # 建议图片大小是 750x1334，780x1387，1125x2436，1242x2208 等移动设备的分辨率
        avif_url: /assets/slide/mobile-2.avif
        webp_url: /assets/slide/mobile-2.webp
        url: /assets/slide/mobile-2.jpg
      introduce:
        position: left
        title: 阿甘正传
        subtitle: 生活就像一盒巧克力，你永远不知道下一个是什么
        white_title: false
        button_title: 点击查看
        button_url: /
    # 第三组
    # 图片的 url 为普通的 jpg png gif 等图片格式，url 此值不能为空。avif 和 webp 请专门设置
    - desktop_img: # 建议图片大小是 1080P，2K，4K 等以便在 PC 电脑上显示
        avif_url: /assets/slide/3.avif
        webp_url: /assets/slide/3.webp
        url: /assets/slide/3.jpg
      tablet_img: # 建议图片大小是 768x1024，1024x1336，1536x2048，2048x2732 等平板设备的分辨率
        avif_url: /assets/slide/tablet-3.avif
        webp_url: /assets/slide/tablet-3.webp
        url: /assets/slide/tablet-3.jpg
      mobile_img: # 建议图片大小是 750x1334，780x1387，1125x2436，1242x2208 等移动设备的分辨率
        avif_url: /assets/slide/mobile-3.avif
        webp_url: /assets/slide/mobile-3.webp
        url: /assets/slide/mobile-3.jpg
      introduce:
        position: right
        title: Actions
        subtitle: To learn to be just and constant, not just is sui Hui, not constant retreat
        white_title: true
        button_title: Read more
        button_url: /
########################### Slide ########################### > end
