########################### Head ########################### > start
# site-related configuration
# 站点相关配置
site:
  favicon: /favicon.ico
  logo: /favicon.ico
  display_title: true #显示站点名称, true 为显示, false 为不显示

# DNS 预解析 dns-prefetch preconnect
preconnect:
  - https://cdnjs.cloudflare.com/
  # - https://cdn.jsdelivr.net/
  # - https://unpkg.com/

# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
    # - <link rel="stylesheet" href="/xxx.css">
  bottom:
    # - <script src="xxxx"></script>

# 404 page
error_404:
  enable: true

########################### Head ########################### > end


########################### Navigation Bar ########################### > start
# 注意事项：建议规范全站路径 link 最后带一个 "/" 例如 "about/"
# main menu navigation
menu:
  # Home: /
  # List:
  #   Item1: /
  #   Item2: /
  # Link: /
  # About: /about/

# mobile menu navigation, Do not have a submenu
mobile_menu:
  # Link: /
  # Docs: /
  # About: /about/
  # Contact: /

# mobile menu scroll, If not enabled, please set enable to false
mobile_menu_scroll:
  enable: true
  before: /assets/nav/menu-scroll-before.webp
  after: /assets/nav/menu-scroll-after.webp

# Navigation bar right-side button
nav_button:
  enable: true #导航栏右侧按钮总开关, 设置 false 为不显示, 以下所有按钮开启了也不会显示
  container:
    enable: true #在导航栏显示内容按钮, 设置 false 为不显示
    text: Get started
    link: /

########################### Navigation Bar ########################### > end


########################### Home Slide ########################### > start
slide:
  enable: true
  wrapper:
    # TODO: 后续有时间实现 introduce
    # 第一组
    # 图片的 link 为普通的 jpg png gif 等图片格式, link 此值不能为空. avif 和 webp 请专门设置
    - desktop_img: # 建议图片大小是 1080P, 2K, 4K 等以便在 PC 电脑上显示
        avif_link: /assets/slide/1.avif
        webp_link: /assets/slide/1.webp
        link: /assets/slide/1.jpg
      tablet_img: # 建议图片大小是 768x1024, 1024x1336, 1536x2048, 2048x2732 等平板设备的分辨率
        avif_link: /assets/slide/tablet-1.avif
        webp_link: /assets/slide/tablet-1.webp
        link: /assets/slide/tablet-1.jpg
      mobile_img: # 建议图片大小是 750x1334, 780x1387, 1125x2436, 1242x2208 等移动设备的分辨率
        avif_link: /assets/slide/mobile-1.avif
        webp_link: /assets/slide/mobile-1.webp
        link: /assets/slide/mobile-1.jpg
      introduce:
        position: center
        title: Getting
        subtitle: Wit once bought is worth twice taught
        white_font: false
        button:
          style: primary # 按钮的样式风格
          text: Read more
          link: /
    # 第二组
    # 图片的 link 为普通的 jpg png gif 等图片格式, link 此值不能为空. avif 和 webp 请专门设置
    - desktop_img: # 建议图片大小是 1080P, 2K, 4K 等以便在 PC 电脑上显示
        avif_link: /assets/slide/2.avif
        webp_link: /assets/slide/2.webp
        link: /assets/slide/2.jpg
      tablet_img: # 建议图片大小是 768x1024, 1024x1336, 1536x2048, 2048x2732 等平板设备的分辨率
        avif_link: /assets/slide/tablet-2.avif
        webp_link: /assets/slide/tablet-2.webp
        link: /assets/slide/tablet-2.jpg
      mobile_img: # 建议图片大小是 750x1334, 780x1387, 1125x2436, 1242x2208 等移动设备的分辨率
        avif_link: /assets/slide/mobile-2.avif
        webp_link: /assets/slide/mobile-2.webp
        link: /assets/slide/mobile-2.jpg
      introduce:
        position: left
        title: 阿甘正传
        subtitle: 生活就像一盒巧克力，你永远不知道下一个是什么
        white_font: false
        button:
          style: primary # 按钮的样式风格
          text: 点击查看
          link: /
    # 第三组
    # 图片的 link 为普通的 jpg png gif 等图片格式, link 此值不能为空. avif 和 webp 请专门设置
    - desktop_img: # 建议图片大小是 1080P, 2K, 4K 等以便在 PC 电脑上显示
        avif_link: /assets/slide/3.avif
        webp_link: /assets/slide/3.webp
        link: /assets/slide/3.jpg
      tablet_img: # 建议图片大小是 768x1024, 1024x1336, 1536x2048, 2048x2732 等平板设备的分辨率
        avif_link: /assets/slide/tablet-3.avif
        webp_link: /assets/slide/tablet-3.webp
        link: /assets/slide/tablet-3.jpg
      mobile_img: # 建议图片大小是 750x1334, 780x1387, 1125x2436, 1242x2208 等移动设备的分辨率
        avif_link: /assets/slide/mobile-3.avif
        webp_link: /assets/slide/mobile-3.webp
        link: /assets/slide/mobile-3.jpg
      introduce:
        position: right
        title: Actions
        subtitle: To learn to be just and constant, not just is sui Hui, not constant retreat
        white_font: true
        button:
          style: primary # 按钮的样式风格
          text: Read more
          link: /
########################### Home Slide ########################### > end


########################### Home Section ########################### > start
section:
  for_home: [] # [kernel, kernel_cards, content, content_cards] # hexo 使用 deepMerge 库会导致读取双重配置，默认为空
  use_simple_parallax: true # true 为使用 simpleParallax 视差效果, false 不使用
  library:
    # --------------- Section -> Library -> Kernel Banner --------------- > start
    # 网站的核心信息组件
    kernel:
      white_font: false #字体颜色, false 为黑色, true 为白色
      # banner 的背景, 建议使用渐变颜色, 示例：'linear-gradient(180deg, 颜色hex 0%, 颜色hex 100%)'
      background_image: 'linear-gradient(180deg, #fffefe 0%, #efebe2 100%)'
      badge: declaration #标语的徽标, 为空不显示
      title:
        - text: Light tomorrow with today.
        - text: Time is that we do not come loose.
        # - text: 这是没有显示出来的第三行标题, 支持多行标题, 不建议超过三行
      description:
        - text: A friend is one of the nicest things you can have, and one of the best things you can be.
        - text: Friendship is a sheltering tree.
        # - 这是没有显示出来的第三行内容文本, 支持多行文本, 不宜过多
      img: # 图片的 link 为普通的 jpg png gif 等图片格式, link 此值不能为空. avif 和 webp 请专门设置
        avif_link: /assets/banner/kernel-banner.avif
        webp_link: /assets/banner/kernel-banner.webp
        link: /assets/banner/kernel-banner.png
        alt: banner image
      button:
        style: primary # 按钮的样式风格
        text: Learn more # 按钮的文本, 同按钮链接一样, 为空则不显示按钮
        link: / # 按钮的链接, 同按钮文本一样, 为空则不显示按钮
    # --------------- Section -> Library -> Kernel Banner --------------- > end

    # --------------- Section -> Library -> Cards Banner --------------- > start
    # 卡片组, 图片尽量选有透明通道的
    kernel_cards:
      # 卡片组的上面部分
      top:
        enable: false
        left:
          background_color: '#F2F2F3'
          text:
            enable: false # 是否显示文字 true 为显示, false 为不显示
            title: Quality is the goal
            description: A friend is one of the nicest things you can have, and one of the best things you can be.
            white_font: false #字体颜色, false 为黑色, true 为白色
          img:
            avif_link: /assets/banner/cards-top-left.avif
            webp_link: /assets/banner/cards-top-left.webp
            link: /assets/banner/cards-top-left.png
            alt: banner image
        right:
          background_color: '#F2F2F3'
          img:
            avif_link: /favicon.ico
            webp_link: /favicon.ico
            link: /favicon.ico
            alt: banner image
          text:
            enable: false # 是否显示文字 true 为显示, false 为不显示
            title: Quality is the goal
            description: A friend is one of the nicest things you can have, and one of the best things you can be.
            white_font: false #字体颜色, false 为黑色, true 为白色
      # 卡片组的中间部分
      center:
        enable: false
        background_color: '#F2F2F3'
        img:
          desktop_img:
            avif_link: /assets/slide/3.avif
            webp_link: /assets/slide/3.webp
            link: /assets/slide/3.jpg
          mobile_img:
            avif_link: /assets/slide/mobile-3.avif
            webp_link: /assets/slide/mobile-3.webp
            link: /assets/slide/mobile-3.jpg
          alt: banner image
        text:
          enable: false # 是否显示文字 true 为显示, false 为不显示
          title: Quality is the goal
          description: A friend is one of the nicest things you can have, and one of the best things you can be.
          white_font: true #字体颜色, false 为黑色, true 为白色
      # 卡片组的下面部分
      bottom:
        enable: false
        left:
          background_color: '#F2F2F3'
          img:
            avif_link: /assets/slide/2.avif
            webp_link: /assets/slide/2.webp
            link: /assets/slide/2.jpg
            alt: banner image
          text:
            enable: false # 是否显示文字 true 为显示, false 为不显示
            title: Quality is the goal
            description: A friend is one of the nicest things you can have, and one of the best things you can be.
            white_font: false #字体颜色, false 为黑色, true 为白色
        right:
          background_color: '#F2F2F3'
          img:
            avif_link: /assets/slide/1.avif
            webp_link: /assets/slide/1.webp
            link: /assets/slide/1.jpg
            alt: banner image
          text:
            enable: false # 是否显示文字 true 为显示, false 为不显示
            title: Quality is the goal
            description: A friend is one of the nicest things you can have, and one of the best things you can be.
            white_font: false #字体颜色, false 为黑色, true 为白色
    # --------------- Section -> Library -> Cards Banner --------------- > end

    # --------------- Section -> Library -> Content Banner --------------- > start
    # 网站的内容组件
    content:
      white_font: true #字体颜色, false 为黑色, true 为白色
      # banner 的背景, 建议使用渐变颜色, 示例：'linear-gradient(180deg, 颜色hex 0%, 颜色hex 100%)'
      background_image: 'linear-gradient(180deg, #434343 0%, #161718 100%)'
      badge: declaration #标语的徽标, 为空不显示
      title:
        - text: Light tomorrow with today.
        - text: Time is that we do not come loose.
        # - 这是没有显示出来的第三行标题, 支持多行标题, 不建议超过三行
      description:
        - text: A friend is one of the nicest things you can have, and one of the best things you can be.
        - text: Friendship is a sheltering tree.
        # - 这是没有显示出来的第三行内容文本, 支持多行文本, 不宜过多
      img: # 图片的 link 为普通的 jpg png gif 等图片格式, link 此值不能为空. avif 和 webp 请专门设置
        avif_link: /assets/banner/content-banner.avif
        webp_link: /assets/banner/content-banner.webp
        link: /assets/banner/content-banner.png
        alt: banner image
      button:
        style: primary # 按钮的样式风格
        text: Learn more # 按钮的文本, 同按钮链接一样, 为空则不显示按钮
        link: / # 按钮的链接, 同按钮文本一样, 为空则不显示按钮
    # --------------- Section -> Library -> Kernel Banner --------------- > end

    # --------------- Section -> Library -> Cards Banner --------------- > start
    # 卡片组, 图片尽量选有透明通道的
    content_cards:
      # 卡片组的上面部分
      top:
        enable: false
        left:
          background_color: '#F2F2F3'
          text:
            enable: false # 是否显示文字 true 为显示, false 为不显示
            title: Quality is the goal
            description: A friend is one of the nicest things you can have, and one of the best things you can be.
            white_font: false #字体颜色, false 为黑色, true 为白色
          img:
            avif_link: /assets/banner/cards-top-left.avif
            webp_link: /assets/banner/cards-top-left.webp
            link: /assets/banner/cards-top-left.png
            alt: banner image
        right:
          background_color: '#F2F2F3'
          img:
            avif_link: /favicon.ico
            webp_link: /favicon.ico
            link: /favicon.ico
            alt: banner image
          text:
            enable: false # 是否显示文字 true 为显示, false 为不显示
            title: Quality is the goal
            description: A friend is one of the nicest things you can have, and one of the best things you can be.
            white_font: false #字体颜色, false 为黑色, true 为白色
      # 卡片组的中间部分
      center:
        enable: false
        background_color: '#F2F2F3'
        img:
          desktop_img:
            avif_link: /assets/slide/3.avif
            webp_link: /assets/slide/3.webp
            link: /assets/slide/3.jpg
          mobile_img:
            avif_link: /assets/slide/mobile-3.avif
            webp_link: /assets/slide/mobile-3.webp
            link: /assets/slide/mobile-3.jpg
          alt: banner image
        text:
          enable: false # 是否显示文字 true 为显示, false 为不显示
          title: Quality is the goal
          description: A friend is one of the nicest things you can have, and one of the best things you can be.
          white_font: true #字体颜色, false 为黑色, true 为白色
      # 卡片组的下面部分
      bottom:
        enable: false
        left:
          background_color: '#F2F2F3'
          img:
            avif_link: /assets/slide/2.avif
            webp_link: /assets/slide/2.webp
            link: /assets/slide/2.jpg
            alt: banner image
          text:
            enable: false # 是否显示文字 true 为显示, false 为不显示
            title: Quality is the goal
            description: A friend is one of the nicest things you can have, and one of the best things you can be.
            white_font: false #字体颜色, false 为黑色, true 为白色
        right:
          background_color: '#F2F2F3'
          img:
            avif_link: /assets/slide/1.avif
            webp_link: /assets/slide/1.webp
            link: /assets/slide/1.jpg
            alt: banner image
          text:
            enable: false # 是否显示文字 true 为显示, false 为不显示
            title: Quality is the goal
            description: A friend is one of the nicest things you can have, and one of the best things you can be.
            white_font: false #字体颜色, false 为黑色, true 为白色
    # --------------- Section -> Library -> Cards Banner --------------- > end

########################### Home Section ########################### > end


########################### Aside ########################### > start
aside:
  enable: true
  position: left # 左边右边 right/left

########################### Aside ########################### > end


########################### Footer ########################### > start
footer:
  site:
    enable: true # 是否开启网站介绍信息, true 为启用, false 为不启用
    title: # 不设置则显示 hexo 配置文件的 title
    description: # 不设置则显示 hexo 配置文件的 description
  list_group:
    # - list_title: Who we are
    #   item:
    #     - text: About Us
    #       link: /
    #       open: in # in 为原窗口打开, out 为新窗口打开
    #     - text: FAQ
    #       link: /
    #       open: in # in 为原窗口打开, out 为新窗口打开
    #     - text: Contact Us
    #       link: /
    #       open: in # in 为原窗口打开, out 为新窗口打开
    # - list_title: Who we are
    #   item:
    #     - text: About Us
    #       link: /
    #       open: in # in 为原窗口打开, out 为新窗口打开
    #     - text: FAQ
    #       link: /
    #       open: in # in 为原窗口打开, out 为新窗口打开
    #     - text: Contact Us
    #       link: /
    #       open: in # in 为原窗口打开, out 为新窗口打开
  copyright: Copyright © 2008 - 2023 Apexfolio. All rights reserved.
  links:
    # - text: Privacy Policy
    #   link: /
    #   open: in # in 为原窗口打开, out 为新窗口打开
    #   external: false # 是否外部链接, false 为内部链接, true 会加上 external nofollow noreferrer noopener
    # - text: Terms of Use
    #   link: /
    #   open: in # in 为原窗口打开, out 为新窗口打开
    #   external: false # 是否外部链接, false 为内部链接, true 会加上 external nofollow noreferrer noopener
    # - text: Cookies
    #   link: /
    #   open: in # in 为原窗口打开, out 为新窗口打开
    #   external: false # 是否外部链接, false 为内部链接, true 会加上 external nofollow noreferrer noopener

########################### Footer ########################### > end


########################### Extra features ########################### > start
# 预加载 https://instant.page/
instantpage: true
########################### Extra features ########################### > end


########################### Import ########################### > start
# TODO：这个不要使用，后续可能会配合全局 loading，目前功能缺失
imagesloaded:
  cdn:
    enable: false # true 启用, false 不启用。启用后, 本地的 imagesloaded js 将会在 cdn 加载出错时调用
    js:
      src: https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/5.0.0/imagesloaded.pkgd.min.js
      integrity: sha512-kfs3Dt9u9YcOiIt4rNcPUzdyNNO9sVGQPiZsub7ywg6lRW5KuK1m145ImrFHe3LMWXHndoKo2YRXWy8rnOcSKg==
  local:
    js: /js/imagesloaded.pkgd.min.js

# slide 功能的依赖
swiper:
  cdn:
    enable: true # true 启用, false 不启用。启用后, 本地的 swiper js 和 css 将会在 cdn 加载出错时调用
    js:
      src: https://cdnjs.cloudflare.com/ajax/libs/Swiper/10.2.0/swiper-bundle.min.js
      integrity: sha512-QwpsxtdZRih55GaU/Ce2Baqoy2tEv9GltjAG8yuTy2k9lHqK7VHHp3wWWe+yITYKZlsT3AaCj49ZxMYPp46iJQ==
    css:
      href: https://cdnjs.cloudflare.com/ajax/libs/Swiper/10.2.0/swiper-bundle.min.css
      integrity: sha512-s6khMl5GDS1HbQ5/SwL1wzMayPwHXPjKoBN5kHUTDqKEPkkGyEZWKyH2lQ3YO2q3dxueG3rE0NHjRawMHd2b6g==
  local:
    js: /js/swiper-bundle.min.js
    css: /css/swiper-bundle.min.css

# 只有在 section 开启 use_simple_parallax 才会加载 simpleParallax.min.js
simple_parallax:
  cdn:
    enable: true # true 启用, false 不启用。启用后, 本地的 simpleParallax js 将会在 cdn 加载出错时调用
    js:
      src: https://cdnjs.cloudflare.com/ajax/libs/simple-parallax-js/5.6.2/simpleParallax.min.js
      integrity: sha512-rLJmRoYJNB5AXXLAElKPeaSrcXDUTA41fiwTZ+S2JJXhMoWu4yQZvXlZZSIjRNVHYTkIYYw+r45wXCao49D5XA==
  local:
    js: /js/simpleParallax.min.js

lenis:
  cdn:
    # lenis 使用 jsdelivr 的 cdn 加载会报错，暂时没有找到其他 cdn, 先只加载本地的 js
    enable: false # true 启用, false 不启用。启用后, 本地的 lenis js 将会在 cdn 加载出错时调用
    js:
      src: https://cdn.jsdelivr.net/npm/@studio-freight/lenis@1.0.22/dist/lenis.min.js
      integrity:
  local:
    js: /js/lenis.min.js

gsap:
  cdn:
    enable: true # true 启用, false 不启用。启用后, 本地的 gsap js 将会在 cdn 加载出错时调用
    js:
      src: https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js
      integrity: sha512-16esztaSRplJROstbIIdwX3N97V1+pZvV33ABoG1H2OyTttBxEGkTsoIVsiP1iaTtM8b3+hu2kB6pQ4Clr5yug==
  local:
    js: /js/gsap.min.js

scroll_trigger:
  cdn:
    enable: true # true 启用, false 不启用。启用后, 本地的 ScrollTrigger js 将会在 cdn 加载出错时调用
    js:
      src: https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js
      integrity: sha512-Ic9xkERjyZ1xgJ5svx3y0u3xrvfT/uPkV99LBwe68xjy/mGtO+4eURHZBW2xW4SZbFrF1Tf090XqB+EVgXnVjw==
  local:
    js: /js/ScrollTrigger.min.js

instant_page:
  cdn:
    enable: true # true 启用, false 不启用。启用后, 本地的 ScrollTrigger js 将会在 cdn 加载出错时调用
    js:
      src: https://cdnjs.cloudflare.com/ajax/libs/instant.page/5.2.0/instantpage.min.js
      integrity: sha512-p8l0Kir2Q2O+MWF/+qw2yM2LQQf0+m0AMD0EvGTFFL9vHquAXMRQKuyFBvHdTWpGEgIbXZxd9vjCRPUHeAhsOA==
  local:
    js: /js/instantpage.min.js
########################### Import ########################### > end
